---
- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false
  ignore_errors: false

- name: Check if Docker Compose is installed
  ansible.builtin.command: docker compose version
  register: docker_compose_version
  changed_when: false
  ignore_errors: false

- name: Create the docker-compose directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/docker-compose"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy the docker-compose.yml file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "/home/{{ ansible_user }}/docker-compose/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Start containers with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/docker-compose"
    state: present
  become: true
